%YAML:1.0

#common parameters
dataset: "ETH"
pathDataset: "/home/lab/slamData/ETH-3D/"

Camera.fx: 726.28741455078
Camera.fy: 726.28741455078
Camera.cx: 354.6496887207
Camera.cy: 186.46566772461

Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0

DepthMapFactor: 5000.0

#parameters for coarse tracking
coarse.width: 739
coarse.height: 458
coarse.kf_trans_thres: 0.01
coarse.kf_rot_thres: 0.4
coarse.sample_bias: 5
coarse.maximum_point: 2000
coarse.cannyHigh: 20
coarse.cannyLow: 10


#parameters for fine tracking
fine.kf_trans_thres: 0.05
fine.kf_rot_thres: 7
fine.geo_photo_ratio: 0.01 
fine.sample_bias: 4 #sample bias for each fine edge
fine.cannyHigh: 30
fine.cannyLow: 15

win.kf_trans_thres: 0.02
win.kf_rot_thres: 4
win.window_size: 10
win.window_step: 7