%YAML:1.0

#common parameters
dataset: "TUM"
pathDataset: "/home/lab/TUM/"

Camera.fx: 517.306408
Camera.fy: 516.469215
Camera.cx: 318.643040
Camera.cy: 255.313989

Camera.k1: 0.262383
Camera.k2: -0.953104
Camera.p1: -0.005358
Camera.p2: 0.002628
Camera.k3: 1.163314

DepthMapFactor: 5000.0

#parameters for coarse tracking
coarse.kf_trans_thres: 0.03
coarse.kf_rot_thres: 0.1
coarse.sample_bias: 7
coarse.maximum_point: 1500
coarse.cannyHigh: 40
coarse.cannyLow: 20


#parameters for fine tracking
fine.kf_trans_thres: 0.04
fine.kf_rot_thres: 3
fine.geo_photo_ratio: 0.01 
fine.sample_bias: 4 #sample bias for each fine edge
fine.cannyHigh: 50
fine.cannyLow: 30