%YAML:1.0

#common parameters
dataset: "TUM"
pathDataset: "/home/lab/slamData/TUM-RGBD/"

Camera.fx: 520.908620
Camera.fy: 521.007327
Camera.cx: 325.141442
Camera.cy: 249.701764

Camera.k1: 0.231222
Camera.k2: -0.784899
Camera.p1: -0.003257
Camera.p2: -0.000105
Camera.k3: 0.917205

DepthMapFactor: 5208.0

#parameters for coarse tracking
coarse.kf_trans_thres: 0.03
coarse.kf_rot_thres: 7
coarse.sample_bias: 7
coarse.maximum_point: 1500
coarse.cannyHigh: 50
coarse.cannyLow: 30


#parameters for fine tracking
fine.kf_trans_thres: 0.05
fine.kf_rot_thres: 7
fine.geo_photo_ratio: 1
fine.sample_bias: 3 #sample bias for each fine edge
fine.cannyHigh: 50
fine.cannyLow: 30