%YAML:1.0

#common parameters
dataset: "TUM"
pathDataset: "/home/lab/TUM/"

Camera.fx: 535.4
Camera.fy: 539.2
Camera.cx: 320.1
Camera.cy: 247.6

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

DepthMapFactor: 5000

#parameters for coarse tracking
coarse.kf_trans_thres: 0.03
coarse.kf_rot_thres: 4
coarse.sample_bias: 15
coarse.maximum_point: 1500
coarse.cannyHigh: 120
coarse.cannyLow: 60


#parameters for fine tracking
fine.kf_trans_thres: 0.05
fine.kf_rot_thres: 7
fine.geo_photo_ratio: 0.01 
fine.sample_bias: 8 #sample bias for each fine edge
fine.cannyHigh: 120
fine.cannyLow: 60