%YAML:1.0

#common parameters
dataset: "TST"
pathDataset: "/home/lab/TST/"

Camera.fx: 385.501
Camera.fy: 385.011
Camera.cx: 323.426
Camera.cy: 243.241

Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0

DepthMapFactor: 1000

#parameters for coarse tracking
coarse.kf_trans_thres: 0.01
coarse.kf_rot_thres: 2
coarse.sample_bias: 7
coarse.maximum_point: 1500
coarse.cannyHigh: 80
coarse.cannyLow: 40


#parameters for fine tracking
fine.kf_trans_thres: 0.05
fine.kf_rot_thres: 7
fine.geo_photo_ratio: 0.01 
fine.sample_bias: 4 #sample bias for each fine edge
fine.cannyHigh: 50
fine.cannyLow: 30